### ISSUE TITLE
Traits 6.1.0 release checklist

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#1120]
## Pre-release

- [x] Review open issues for anything else that should go into this release.
- [x] Review open PRs
- [x] Check for reference leaks (see #725 for hints)
- [x] Test against other ETS packages and other traits-using projects.
- [x] Update changelog. (Use for example `git log 6.0.0..HEAD --pretty="* %s"`).
- [x] Prepare release notes (to be included in the changelog)

## Release

- [x] Create PR to bump version on master for continued development towards 6.2.0; merge that PR (after suitable review) (#1146)
- [x] Make release branch (`release/6.1.x`) from master, branching from the commit immediately preceding the version bump in the previous step; push it to GitHub
- [x] Backport relevant PRs from master branch. (#1167)
- [x] Put correct release date into changelog. (#1168)
- [x] Bump version on release branch. (#1168)
- [x] Tag (annotated tag, please!), and push the tag
- [x] Update release information on GitHub
- [x] Test the package! (Create sdist, install from sdist, check tests pass.)
- [x] PyPI upload
- [x] Test PyPI packages (run tests in a `pip`-installed environment)
- [x] Announce on appropriate channels

## Post-release

- [x] Buildsystem issue for package update. (enthought/buildsystem#3170)
- [x] Build and upload documentation (see wiki page for documentation building HOWTO). (#1192)
- [x] Cherry-pick any necessary changes back into master. (#1193)

**Comment by mdickinson** [comment]
I've re-run the reference leak checks, and apart from the already documented leaks seen with TraitsUI, it all looks good.

**Comment by mdickinson** [comment]
All done. Closing.
