### ISSUE TITLE
Release Traits 4.5.0

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#155]
Checklist:
- [x] Branch new release/4.5.0 branch from master.
- [x] Bump release number to 4.5.0-rc.1.
- [x] Review outstanding PRs for potential inclusion.
- [x] Review CHANGES.txt w.r.t. recent PRs; update if necessary. (See PR #156.)
- [x] Check tests.
- [x] Create release-docs/4.5.0 branch for gh-pages documentation.
- [x] Build and check documentation.
- [x] Make sure that we're including relevant non-code files (LICENSE, README) in the distribution.  (Issue #127)
- [x] Tag 4.5.0 release candidate from the release/4.5.0 branch.
- [x] In master: bump release number to 4.6.0-alpha; prepare CHANGES.txt for updates. (PR #164.)
- [x] Run tests for other ETS projects against the 4.5.0 release branch.
- [x] Add ReadTheDocs build for the release branch.
- [x] Announce the rc; give devs some days to review.
- [x] Verify build and tests on Windows. (Jenkins currently not running.)
- [x] If all's well, bump version number to 4.5.0 and make the release.
- [x] Merge release branch back into master.
