### ISSUE TITLE
Traits 6.3.0 release checklist

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#1553]
Things not to forget for the 6.3.0 release. Some of these should probably be broken out into their own issues.

- [ ] For the release notes, include a list of pending deprecations that will hit in Traits 7.0.0.
- [ ] Check that ETS demo works
- [ ] Update wheel-building machinery to include Python 3.10 (this may be a bit awkward: we'll have to temporarily use a dev version of Python 3.10 on GitHub Actions)

**Comment by mdickinson** [comment]
> * we'll have to temporarily use a dev version of Python 3.10 on GitHub Actions

Or possibly not. We've procrastinated long enough that 3.10 is quite likely to be out before Traits 6.3.0. Not sure how long it will take GitHub Actions to catch up.
