### ISSUE TITLE
Traits 5.2.0 release checklist.

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#561]
- [x] Review open PRs
    - [x] #559 needs review and merge
    - [x] #560 needs review and merge
    - [x] #563 needs merge
- [x] Review open issues for anything else that should go into this release.
- [x] Update changelog (#562)
- [x] Make release branch (`release/5.2.x`) from master; push it to GitHub
- [x] Bump version on master for continued development (#564)
- [x] Bump version on release branch (#565)
- [x] Testing! (Create sdist, install from sdist, check tests pass.)
- [x] Tag
- [x] Testing!
- [x] Update release information on GitHub
- [x] PyPI upload
- [x] More testing!
- [x] Build and upload documentation.
- [x] Buildsystem issue for package update (internal buildsystem issue: enthought/buildsystem#2726)
- [x] Bring any necessary changes back into master (nothing to do this time around)

---

After eggs are built for EDM:

- [x] One more round of testing with the EDM eggs
- [x] Announce the release (Slack, portal, ets-users)

**Comment by mdickinson** [comment]
All done. Closing.
