### ISSUE TITLE
Traits 6.0.0 release checklist

### ISSUE THREAD

**Issue by mdickinson** [enthought/traits#839]
The plan is to make a 6.0 release candidate and push it to PyPI (but not release on EDM), then encourage testing with that release candidate. If all goes well, that will be followed by a full release and an EDM release. Some of the instructions below need to be modified accordingly.

- [x] Review open PRs
- [x] Review open issues for anything else that should go into this release.
- [x] Create PR to bump version on master for continued development towards 6.1.0; merge that PR (after suitable review)
- [x] Make release branch (`release/6.0.x`) from master, branching from the commit immediately preceding the version bump in the previous step; push it to GitHub
- [x] Update changelog. (Use for example `git log 5.2.0..HEAD --pretty="* %s"`). (PR: #841)
- [x] Pre-release testing.

Make the release.

- [x] Put correct release date into changelog. (#846)
- [x] Bump version on release branch. (#846)
- [x] Tag (annotated tag, please!), and push the tag
- [x] Update release information on GitHub
- [x] PyPI upload (make sure that the package is marked as prerelease)
- [x] Announce on appropriate channels

- [x] Test the package! (Create sdist, install from sdist, check tests pass.)
- [x] Test against other ETS packages and other traits-using projects.
- [x] More testing!
- [x] Build and upload documentation. (#899)
- [x] Buildsystem issue for package update. (enthought/buildsystem#2944)
- [x] Bring any necessary changes back into master (setup.py changes for prerelease, changelog). (#900)

Final release

- [x] Update changelog, bump version for final release. (#859)

**Comment by mdickinson** [comment]
Calling this done, though #900 is still pending.

**Comment by mdickinson** [comment]
#900 is now merged, and this is *really* done.
